### ISSUE TITLE
Thought you might find this interesting

### ISSUE THREAD

**Issue by PikaMug** [Redned235/SimReader#1]
I see you're targeting SimCity 4, but may find this relevant:
https://github.com/jgosar/mine-city-2000

Cheers!

**Comment by Redned235** [comment]
Aha yeah I’ve seen this, sadly Sim City 2000 is completely different when it comes to how data is saved compared to SC4, so there isn’t much it really helps with :(. At some point I think it’d be neat to accomplish something similar as Mine City but for SC4, but it’d definitely be a lot more ambitious for sure.

**Comment by anonhostpi** [comment]
Out of curiosity, does SC 2000 use DBPF?
